strategy: QuarterlyTrendFollowing
market: btc-quarterly
coin: btc
days: 4

params:
  shortMaPeriod: 3
  longMaPeriod: 12
  adxPeriod: 5
  adxThreshold: 39.5
  atrPeriod: 6
  atrStopMultiple: 2.25
  targetBuyPrice: 0.13
  targetSellPrice: 0.80
  targetSize: 10
  cutoffMinute: 9
